### ISSUE TITLE
Add back in some images but at a lower resolution

### ISSUE THREAD

**Issue by jzwart** [eco4cast/efi-ci-workshop-2024#8]
I removed most images from the repository because they took up a lot of space and were 6-10Mb / photo. We could add some photos back in but have them at a lower resolution. Other images https://github.com/eco4cast/efi-ci-workshop-2024/blob/main/images/images-notes

Also would be good to add a section in the 'how to contribute' about lowering resolution of images before adding to the repository.

**Comment by mhpob** [comment]
Could I suggest building in the reduction of image sizes into the GH Actions workflow, either baked in to the Quarto action or in another step that the build-and-deploy action depends on?

I'm imagining installing ffmpeg on the runner, finding image files over X file size, having ffmpeg compress the images, and then committing the images to the repository.

I'm happy to attack this and submit a PR if it's of interest.

**Comment by jzwart** [comment]
That would be great @mhpob ! Yes, if you're up for taking that on then please submit a PR. And glad you reached out - that was the intention of the newsletter :)
